ParalletDirectoryWebApp/Models/ErrorViewModel.cs
using System;

namespace ParalletDirectoryWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ParalletDirectoryWebApp/Models/Folder.cs
using System.ComponentModel.DataAnnotations;

namespace ParalletDirectoryWebApp.Models
{
    public class Folder
    {
        [Key]
        public int Folderid { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    }
}

ParalletDirectoryWebApp/Models/ParallelContext.cs
using Microsoft.EntityFrameworkCore;

namespace ParalletDirectoryWebApp.Models
{
    public partial class ParallelContext : DbContext
    {
        public ParallelContext()
        {             
        }

        public ParallelContext(DbContextOptions<ParallelContext> options) : base(options)
        {            
        }

        public virtual DbSet<Folder> Folders { get; set; }

        public virtual DbSet<TextFile> TextFiles { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("name=ConnectionStrings:ParalletDirectoryWebAppContext");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<Folder>(entity =>{
                entity.ToTable("Folders");

                entity.Property(e => e.Folderid).HasColumnName("Folderid");

                entity.Property(e => e.Name)
                .IsRequired();

                entity.Property(e => e.Location)
                .IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    }
}

ParalletDirectoryWebApp/Models/TextFile.cs
using System.ComponentModel.DataAnnotations;

namespace ParalletDirectoryWebApp.Models
{
    public class TextFile
    {
        [Key]
        public int TextFileid { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    }
}

ParalletDirectoryWebApp/Controllers/FolderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ParalletDirectoryWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace ParalletDirectoryWebApp.Controllers
{
    public class FolderController : Controller
    {
        private readonly ParallelContext _context;

        public FolderController(ParallelContext context)
        {
            _context = context;
        }

        // GET: FolderController
        public ActionResult Index()
        {
            var model = _context.Folders.ToList();
            return View(model);
        }
        //s
        // GET: FolderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FolderController/Create
        public ActionResult Create()
        {
            ViewBag.Folders = _context.Folders.ToList().OrderBy(x => x.Folderid)
                .Select(x => new
                {
                    Folderid = x.Folderid,
                    Location = x.Location + "/" + x.Name
                });
            return View();
        }

        // POST: FolderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Folder model)
        {
            _context.Add(model);
            _context.SaveChanges();

            return RedirectToAction("index");
        }

        // GET: FolderController/Edit/5
        public ActionResult Edit(int id)
        {
            var folders = _context.Folders.ToList();

            ViewBag.Folders = folders.Select(a => new
            {
                Folderid = a.Folderid,
                Location = a.Location
            }).Where(b => b.Folderid == id).Union(
                folders.OrderBy(x => x.Folderid)
                .Select(x => new
                {
                    Folderid = x.Folderid,
                    Location = x.Location + "/" + x.Name
                }).Where(y => y.Folderid != id)
                );

            var model = _context.Folders.Find(id);
            return View(model);
        }

        // POST: FolderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Folder model)
        {


            _context.Update(model);
            _context.SaveChanges();

            return View();
        }

        // GET: FolderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FolderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ParalletDirectoryWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ParalletDirectoryWebApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ParalletDirectoryWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        //private readonly ParallelContext _context;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //var model = _context.Folders.ToList();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ParalletDirectoryWebApp/Views/Folder/Create.cshtml
@model ParalletDirectoryWebApp.Models.Folder
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Folder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Location" class="control-label"></label>
                    <input asp-for="Location" class="form-control" type="url"/>
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>*@
            @*@(new SelectList(ViewBag.Folders,"Folderid","Location").Distinct())*@
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <select asp-for="Location" class="form-control" asp-items="@(new SelectList(ViewBag.Folders,"Location","Location"))" >
                    <option selected>@Configuration.GetSection("Paths")["ServerPath"]</option>
                </select>
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ParalletDirectoryWebApp/Views/Folder/Delete.cshtml
@model ParalletDirectoryWebApp.Models.Folder

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Folder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Folderid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ParalletDirectoryWebApp/Views/Folder/Edit.cshtml
@model ParalletDirectoryWebApp.Models.Folder
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Folder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Folderid" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Location" class="control-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <select asp-for="Location" class="form-control" asp-items="@(new SelectList(ViewBag.Folders,"Folderid","Location"))">
                </select>
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ParalletDirectoryWebApp/Views/Folder/Index.cshtml
@model IEnumerable<Folder>
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<h1>Path:</h1>
<h3>@Configuration.GetSection("Paths")["ServerPath"].Split("\\")[1]</h3>
<div class=""></div>
<table>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @*@Html.DisplayFor(modelItem => item.Name)*@
                @if (item.Location == Configuration.GetSection("Paths")["ServerPath"])
                {
                    @item.Name
                    <a class="fa-solid fa-pen-to-square" asp-action="Edit" asp-route-id="@item.Folderid">Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Folderid">Delete</a>
                }
            </td>
        </tr>
    }
</table>

ParalletDirectoryWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ParalletDirectoryWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParalletDirectoryWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ParalletDirectoryWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                    <div class="container">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                Folders
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="Folder" asp-action="Index">Ver Folders</a></li>
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="Folder" asp-action="Create">Agregar Folder</a></li>
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="Folder" asp-action="Edit">Editar Folder</a></li>
                            </ul>
                        </div>                       
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ParalletDirectoryWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>